version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: circle-suzuki/test-container-agent
    steps:
      - run: echo "Hi I'm on Runners!"

