version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.11
    resource_class: circle-suzuki/test-container-agent
    steps:
      - run: echo "Hi I'm on Container Agent!"

workflows:
  build-workflow:
    jobs:
      - build


