version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: circle-suzuki/container-agent
    steps:
      - run: sleep 120
workflows:
  build-workflow:
    jobs:
      - build
